### ISSUE TITLE
Bug ung street fight

### ISSUE THREAD

**Issue by Heavens-c** [JGCdev/xex_streetfight#1]
too fast to end both side wins???

**Comment by JGCdev** [comment]
Sorry but this is not a bug, if you have doubts about how it works you should read the REAMDE.md file or the dedicated post in the forum,
Cheers

**Comment by JGCdev** [comment]
Sorry but this is not a bug, if you have doubts about how it works you should read the REAMDE.md file or the dedicated post in the forum,
Cheers
